POST https://economic-splashy-tennis.glitch.me/login
Content-Type: application/json

{
  "username": "admin"
}

###

DELETE https://economic-splashy-tennis.glitch.me/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MTYzMDYyMzMsImV4cCI6MTcxNjMwNjI2M30.4VU9JoEd9yXuwBnI7US_jxydkGRgKpB0T_MaVfnm6do